### ISSUE TITLE
Should we implement the ability to change home location?

### ISSUE THREAD

**Issue by ghost** [MSMareddy/WebAppSWE#7]
Edit: Check out the new change location branch.

We add a href to nav bar. On click it prompts the user if they want to change location and if yes, changes cookie and home marker. i already tried it out and it works. I was wondering if we should include it in our implementation.
we just need to add this to script section before our places api implementation:
```
window.onload = function(){
	document.getElementById("getLocation").onclick = function() {
		if (navigator.geolocation) {
			if (confirm("Do you want to change to current location?")) {
				navigator.geolocation.getCurrentPosition(showPosition);
			}
		} 
		else {
			alert("Geolocation is not supported by this browser.");
		}
		return false;
	}
	function showPosition(position) {
		var currLocation = position.coords.latitude + ", " + position.coords.longitude;
		var d = new Date();
		d.setTime(d.getTime() + (7*24*60*60*1000));
		var expires = "expires="+ d.toUTCString();
		document.cookie = "latLongCookie=" + currLocation + ";" + expires + ";path=/";
		location.reload(true);
	}
}
```
and this href to our nav bar
```
<li><a id="getLocation" href="/">Change Location</a></li>
```

**Comment by ghost** [comment]
I created a separate branch from master just in case it doesn't work. what do y'all think?

**Comment by masonchamberlain** [comment]
It sounds like a good thing, won't we need to change the search bounds to be around their location or would we just leave it centered at PKI?

**Comment by ghost** [comment]
actually it is, since we set the center value from cookie value. It also works i just spoofed it to different locations mumbai, tokyo etc.

**Comment by masonchamberlain** [comment]
If it all works I don’t see any reason not to push it to main then. I can do some more testing too to make sure it works.

**Comment by ghost** [comment]
alright done, you should be able to change your location if device has gps, Click ok on prompt and allow your device to access location.

we should change the marker name though, it's still set to PKI.

**Comment by masonchamberlain** [comment]
Something broke, I tried changing my location and the map doesn’t load and it does not return any results for any category.

**Comment by ghost** [comment]
oh damn can you check the console?

**Comment by masonchamberlain** [comment]
It seems to be working okay on my computer, there is something about my phone that causes it to break.

**Comment by ghost** [comment]
huh alright, we can't check console on your phone  i suppose. wait i'll push something so that we can log the exception on html content itself.

**Comment by ghost** [comment]
try now
